# Service ID
send_sms:
  # Service name shown in UI
  name: Send SMS
  description: >-
    Send an SMS message using the Textbelt API.
    Requires a valid Textbelt API key to be configured.
  fields:
    phone:
      name: Phone Number
      description: >-
        The recipient's phone number. Must be in international format
        (e.g., +1234567890 for US numbers).
      required: true
      example: "+1234567890"
      selector:
        text:
          type: tel
    message:
      name: Message
      description: The SMS message text to send
      required: true
      example: "Hello from Home Assistant!"
      selector:
        text:
          multiline: true
